### ISSUE TITLE
Use `nu-mode` without `evil`?

### ISSUE THREAD

**Issue by semenInRussia** [pyluyten/emacs-nu#38]
Hi!  I'm not en `evil` user, but I'm a `nushell` user.  How can  I use this package?

**Comment by pyluyten** [comment]
Hi

You may use nu-mode without evil. It has its own features for editing text ( and some other stuff ).

nu-shell seems to be a ... shell rather than a text editing feature. It is possible to add stuff to nu-mode but at the moment nu-mode does not add anything regarding nushell. If you appreciate nu-mode for something, you may want to add it so you leverage the official branch.
